version: '3.3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: jobsearch
    container_name: jobsearch
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000